version: "3.8"

# Do not use volumes for prod

services:
  server:
    image: gcr.io/bogeybuddies-457015/bogeybuddies-server:latest
    build:
      context: .
      platforms:
        - "linux/amd64"
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
