version: "3.8"

# Use volumes for dev for hot reload changes

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
