name: Deploy to Cloud Run on push to dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install server dependencies
        run: npm install

      - name: Check tsc for server
        run: npx tsc --noEmit

      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Check tsc for client
        working-directory: ./client
        run: npx tsc --noEmit

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          docker compose -f docker-compose.prod.yml build

      - name: Push Image to Google Container Registry
        run: |
          docker tag bogeybuddies-server gcr.io/${{ secrets.GCP_PROJECT }}/bogeybuddies-server:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/bogeybuddies-server:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy bogeybuddies --image gcr.io/${{ secrets.GCP_PROJECT }}/bogeybuddies-server:latest
